DEFAULT_ROOT_ID=''
WHOLESOME_HASHTAG=''
TWITAPI_CONSUMER_KEY=''
TWITAPI_CONSUMER_SECRET=''
TWITAPI_TOKEN_KEY=''
TWITAPI_TOKEN_SECRET=''
TWITTER_ID=''


FOLLOWER_CACHE='cache.bin'
SAVE_FILE='save.json'
WHOLESOME_CONTENT='wholesome-content.txt'
